import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "LUNA 금융상식 QUIZ",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="kr">
        <head>
            <link rel='icon' href='/favicon.svg'/>
            <meta name="theme-color" content="#6D87A8"/>
            <meta name="apple-mobile-web-app-status-bar-style" content="#6D87A8"/>
        </head>
        <body className={inter.className}>{children}</body>
        </html>
    );
}
